package com.sinosoft.zcfz.entity.lianghua;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CfReportRowAddDescId generated by hbm2java
 */
@Embeddable
public class ALM_CfReportRowAddDescId implements java.io.Serializable {

	private String tableCode;
	private String colCode;
	private String reportType;

	public ALM_CfReportRowAddDescId() {
	}

	public ALM_CfReportRowAddDescId(String tableCode, String colCode,
			String reportType) {
		this.tableCode = tableCode;
		this.colCode = colCode;
		this.reportType = reportType;
	}

	@Column(name = "TableCode", nullable = false, length = 20)
	public String getTableCode() {
		return this.tableCode;
	}

	public void setTableCode(String tableCode) {
		this.tableCode = tableCode;
	}

	@Column(name = "ColCode", nullable = false, length = 20)
	public String getColCode() {
		return this.colCode;
	}

	public void setColCode(String colCode) {
		this.colCode = colCode;
	}

	@Column(name = "ReportType", nullable = false, length = 2)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ALM_CfReportRowAddDescId))
			return false;
		ALM_CfReportRowAddDescId castOther = (ALM_CfReportRowAddDescId) other;

		return ((this.getTableCode() == castOther.getTableCode()) || (this
				.getTableCode() != null && castOther.getTableCode() != null && this
				.getTableCode().equals(castOther.getTableCode())))
				&& ((this.getColCode() == castOther.getColCode()) || (this
						.getColCode() != null && castOther.getColCode() != null && this
						.getColCode().equals(castOther.getColCode())))
				&& ((this.getReportType() == castOther.getReportType()) || (this
						.getReportType() != null
						&& castOther.getReportType() != null && this
						.getReportType().equals(castOther.getReportType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTableCode() == null ? 0 : this.getTableCode().hashCode());
		result = 37 * result
				+ (getColCode() == null ? 0 : this.getColCode().hashCode());
		result = 37
				* result
				+ (getReportType() == null ? 0 : this.getReportType()
						.hashCode());
		return result;
	}

}
