package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CfCodeManage generated by hbm2java
 */
@Entity
@Table(name = "CfCodeManage")
public class CfCodeManage implements java.io.Serializable {

	private CfCodeManageId id;
	private String typeName;
	private String codeName;
	private String useFlag;
	private String remark;

	public CfCodeManage() {
	}

	public CfCodeManage(CfCodeManageId id, String typeName, String codeName,
			String useFlag) {
		this.id = id;
		this.typeName = typeName;
		this.codeName = codeName;
		this.useFlag = useFlag;
	}

	public CfCodeManage(CfCodeManageId id, String typeName, String codeName,
			String useFlag, String remark) {
		this.id = id;
		this.typeName = typeName;
		this.codeName = codeName;
		this.useFlag = useFlag;
		this.remark = remark;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeType", column = @Column(name = "CodeType", nullable = false, length = 40)),
			@AttributeOverride(name = "codeCode", column = @Column(name = "CodeCode", nullable = false, length = 40)) })
	public CfCodeManageId getId() {
		return this.id;
	}

	public void setId(CfCodeManageId id) {
		this.id = id;
	}

	@Column(name = "TypeName", nullable = false, length = 100)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "CodeName", nullable = false, length = 500)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "UseFlag", nullable = false, length = 1)
	public String getUseFlag() {
		return this.useFlag;
	}

	public void setUseFlag(String useFlag) {
		this.useFlag = useFlag;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
