package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CfReportPeriodDataCheck generated by hbm2java
 */
@Entity
@Table(name = "CfReportPeriodDataCheck")
public class CfReportPeriodDataCheck implements java.io.Serializable {

	private int serialNo; //由String类型修改为int类型 ,并让其自动增长。   modify by liucw
	private String itemCodeBq;
	private String itemCodeSq;
	private String relationOperator;
	private String calType;
	private String remark;
	private String isNeedChk;

	private BigDecimal tolerance;  //容差        add by liucw
	
	@Column(name = "tolerance",  nullable = false)
	public BigDecimal getTolerance() {
		return tolerance;
	}

	public void setTolerance(BigDecimal tolerance) {
		this.tolerance = tolerance;
	}
	
	public CfReportPeriodDataCheck() {
	}

	public CfReportPeriodDataCheck(int serialNo) {
		this.serialNo = serialNo;
	}

	public CfReportPeriodDataCheck(int serialNo, String itemCodeBq,
			String itemCodeSq, String relationOperator, String calType,
			String remark, String isNeedChk) {
		this.serialNo = serialNo;
		this.itemCodeBq = itemCodeBq;
		this.itemCodeSq = itemCodeSq;
		this.relationOperator = relationOperator;
		this.calType = calType;
		this.remark = remark;
		this.isNeedChk = isNeedChk;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "SerialNo", unique = true, nullable = false, length = 10)
	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "ItemCodeBq", length = 50)
	public String getItemCodeBq() {
		return this.itemCodeBq;
	}

	public void setItemCodeBq(String itemCodeBq) {
		this.itemCodeBq = itemCodeBq;
	}

	@Column(name = "ItemCodeSq", length = 50)
	public String getItemCodeSq() {
		return this.itemCodeSq;
	}

	public void setItemCodeSq(String itemCodeSq) {
		this.itemCodeSq = itemCodeSq;
	}

	@Column(name = "RelationOperator", length = 10)
	public String getRelationOperator() {
		return this.relationOperator;
	}

	public void setRelationOperator(String relationOperator) {
		this.relationOperator = relationOperator;
	}

	@Column(name = "CalType", length = 4)
	public String getCalType() {
		return this.calType;
	}

	public void setCalType(String calType) {
		this.calType = calType;
	}

	@Column(name = "Remark", length = 40)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "IsNeedChk", length = 3)
	public String getIsNeedChk() {
		return this.isNeedChk;
	}

	public void setIsNeedChk(String isNeedChk) {
		this.isNeedChk = isNeedChk;
	}

}
