package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CfReportErrInfo generated by hbm2java
 */
@Entity
@Table(name = "CfReportErrInfo")
public class CfReportErrInfo implements java.io.Serializable {

	private BigDecimal id;
	private String year;
	private String comCode;
	private String quarter;
	private String reportType;
	private String checkedCode;  //错误级别 ：  error、warn 
	private String errorInfo;
	private Date checkdate;
	private String temp;
	private String rowNo;
	private String modifyState;
	private Date updateTime;
	private String updateOperator;
	private String modifyLock;
	private BigDecimal tolerance;  //容差        add by liucw
	private String reportId;
	
	@Column(name = "tolerance",  nullable = false)
	public BigDecimal getTolerance() {
		return tolerance;
	}

	public void setTolerance(BigDecimal tolerance) {
		this.tolerance = tolerance;
	}
	@Override
	public String toString() {
		return "CfReportErrInfo [id=" + id + ", year=" + year + ", comCode=" + comCode + ", quarter=" + quarter
				+ ", reportType=" + reportType + ", checkedCode=" + checkedCode + ", errorInfo=" + errorInfo
				+ ", checkdate=" + checkdate + ", temp=" + temp + ", rowNo=" + rowNo + ", modifyState=" + modifyState
				+ ", updateTime=" + updateTime + ", updateOperator=" + updateOperator + ", reportid=" + reportId + ", modifyLock=" + modifyLock
				+ "]";
	}

	public CfReportErrInfo() {
	}

	public CfReportErrInfo(BigDecimal id, String year, String quarter,
			String reportType, String checkedCode, String reportId) {
		this.id = id;
		this.year = year;
		this.quarter = quarter;
		this.reportType = reportType;
		this.checkedCode = checkedCode;
		this.reportId = reportId;
	}

	public CfReportErrInfo(BigDecimal id, String year, String comCode,
			String quarter, String reportType, String checkedCode,
			String errorInfo, Date checkdate, String temp, String rowNo,
			String modifyState, Date updateTime, String updateOperator,
			String modifyLock, String reportId) {
		this.id = id;
		this.year = year;
		this.comCode = comCode;
		this.quarter = quarter;
		this.reportType = reportType;
		this.checkedCode = checkedCode;
		this.errorInfo = errorInfo;
		this.checkdate = checkdate;
		this.temp = temp;
		this.rowNo = rowNo;
		this.modifyState = modifyState;
		this.updateTime = updateTime;
		this.updateOperator = updateOperator;
		this.modifyLock = modifyLock;
		this.reportId = reportId;
	}

	//增加@GeneratedValue(strategy=GenerationType.AUTO) 
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "Year", nullable = false, length = 4)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "ComCode", length = 10)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "Quarter", nullable = false, length = 4)
	public String getQuarter() {
		return this.quarter;
	}

	public void setQuarter(String quarter) {
		this.quarter = quarter;
	}

	@Column(name = "ReportType", nullable = false, length = 4)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Column(name = "CheckedCode", nullable = false, length = 10)
	public String getCheckedCode() {
		return this.checkedCode;
	}

	public void setCheckedCode(String checkedCode) {
		this.checkedCode = checkedCode;
	}

	@Column(name = "ErrorInfo", length = 4000)
	public String getErrorInfo() {
		return this.errorInfo;
	}

	public void setErrorInfo(String errorInfo) {
		this.errorInfo = errorInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Checkdate", length = 7)
	public Date getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	@Column(name = "Temp", length = 4000)
	public String getTemp() {
		return this.temp;
	}

	public void setTemp(String temp) {
		this.temp = temp;
	}

	@Column(name = "RowNo", length = 8)
	public String getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(String rowNo) {
		this.rowNo = rowNo;
	}

	@Column(name = "ModifyState", length = 8)
	public String getModifyState() {
		return this.modifyState;
	}

	public void setModifyState(String modifyState) {
		this.modifyState = modifyState;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UpdateTime", length = 7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "UpdateOperator")
	public String getUpdateOperator() {
		return this.updateOperator;
	}

	public void setUpdateOperator(String updateOperator) {
		this.updateOperator = updateOperator;
	}

	@Column(name = "ModifyLock", length = 8)
	public String getModifyLock() {
		return this.modifyLock;
	}

	public void setModifyLock(String modifyLock) {
		this.modifyLock = modifyLock;
	}

	@Column(name = "ReportId", length = 255, nullable = false)
	public String getReportId() {
		return reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}
	
	
}
