package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CfReportRowDataCheck generated by hbm2java
 */
@Entity
@Table(name = "CfReportRowDataCheck")
public class CfReportRowDataCheck implements java.io.Serializable {

	private int serialNo;   //由String类型修改为int类型 ,并让其自动增长。 modify by liucw
	private String tableCode;
	private String calFormula; //由calFormua修改为 calFormula。     modify  by liucw
	private String calType;
	private String remark;
	private String isNeedChk;

	private BigDecimal tolerance;  //容差        add by liucw
	
	@Column(name = "tolerance",  nullable = false)
	public BigDecimal getTolerance() {
		return tolerance;
	}

	public void setTolerance(BigDecimal tolerance) {
		this.tolerance = tolerance;
	}
	
	public CfReportRowDataCheck() {
	}

	public CfReportRowDataCheck(int serialNo, String calFormula) {
		this.serialNo = serialNo;
		this.calFormula = calFormula;
	}

	public CfReportRowDataCheck(int serialNo, String tableCode,
			String calFormula, String calType, String remark, String isNeedChk) {
		this.serialNo = serialNo;
		this.tableCode = tableCode;
		this.calFormula = calFormula;
		this.calType = calType;
		this.remark = remark;
		this.isNeedChk = isNeedChk;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "SerialNo", unique = true, nullable = false, length = 10)
	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "TableCode", length = 20)
	public String getTableCode() {
		return this.tableCode;
	}

	public void setTableCode(String tableCode) {
		this.tableCode = tableCode;
	}

	@Column(name = "CalFormula", nullable = false, length = 600)
	public String getCalFormula() {
		return this.calFormula;
	}

	public void setCalFormula(String calFormula) {
		this.calFormula = calFormula;
	}

	@Column(name = "CalType", length = 20)
	public String getCalType() {
		return this.calType;
	}

	public void setCalType(String calType) {
		this.calType = calType;
	}

	@Column(name = "Remark", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "IsNeedChk", length = 3)
	public String getIsNeedChk() {
		return this.isNeedChk;
	}

	public void setIsNeedChk(String isNeedChk) {
		this.isNeedChk = isNeedChk;
	}

}
