package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CfReportRowAddDataId generated by hbm2java
 */
@Embeddable
public class CfReportRowAddDataRiskId implements java.io.Serializable {

	
	private String colCode;
	private String rowNo;
	private String reportId;

	public CfReportRowAddDataRiskId() {
	}

	public CfReportRowAddDataRiskId(String colCode, String rowNo, String reportId) {
		this.colCode = colCode;
		this.rowNo = rowNo;
		this.reportId = reportId;
	}

	

	@Column(name = "ColCode", nullable = false, length = 20)
	public String getColCode() {
		return this.colCode;
	}

	public void setColCode(String colCode) {
		this.colCode = colCode;
	}

	@Column(name = "RowNo", nullable = false, length = 8)
	public String getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(String rowNo) {
		this.rowNo = rowNo;
	}
	
	@Column(name = "ReportId", nullable = false, length = 255)
	public String getReportId() {
		return reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CfReportRowAddDataRiskId))
			return false;
		CfReportRowAddDataRiskId castOther = (CfReportRowAddDataRiskId) other;

		return ((this.getReportId() == castOther.getReportId()) || (this
				.getReportId() != null && castOther.getReportId() != null && this
				.getReportId().equals(castOther.getReportId())))
				&& ((this.getColCode() == castOther.getColCode()) || (this
						.getColCode() != null && castOther.getColCode() != null && this
						.getColCode().equals(castOther.getColCode())))
				&& ((this.getRowNo() == castOther.getRowNo()) || (this
						.getRowNo() != null && castOther.getRowNo() != null && this
						.getRowNo().equals(castOther.getRowNo())));
	}

	public int hashCode() {
		int result = 17;

		
		result = 37 * result
				+ (getColCode() == null ? 0 : this.getColCode().hashCode());
		result = 37 * result
				+ (getRowNo() == null ? 0 : this.getRowNo().hashCode());
		
		result = 37
				* result
				+ (getReportId() == null ? 0 : this.getReportId()
						.hashCode());
		return result;
	}

}
