package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CfReportErrInfo generated by hbm2java
 */
@Entity
@Table(name = "CfRiskRatingErrInfo")
public class CfRiskRatingErrInfo implements java.io.Serializable {

	private BigDecimal id;
	private String year;
	private String comCode;
	private String quarter;
	private String reportType;
	private String checkedCode;  
	private String errorInfo;
	private Date checkdate;
	private String temp;
	private String rowNo;
	private String modifyState;
	private Date updateTime;
	private String updateOperator;
	private String modifyLock;
	private String errLevel; //错误级别 ：  error、warn 
	private BigDecimal tolerance;  //容差        add by liucw
	
	@Column(name = "tolerance",  nullable = false)
	public BigDecimal getTolerance() {
		return tolerance;
	}

	public void setTolerance(BigDecimal tolerance) {
		this.tolerance = tolerance;
	}

	public CfRiskRatingErrInfo() {
	}




	//增加@GeneratedValue(strategy=GenerationType.AUTO) 
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "Year", nullable = false, length = 4)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "ComCode", length = 10)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "Quarter", nullable = false, length = 4)
	public String getQuarter() {
		return this.quarter;
	}

	public void setQuarter(String quarter) {
		this.quarter = quarter;
	}

	@Column(name = "ReportType", nullable = false, length = 4)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Column(name = "ErrLevel", nullable = false, length = 10)
	public String getErrLevel() {
		return errLevel;
	}

	public void setErrLevel(String errLevel) {
		this.errLevel = errLevel;
	}

	@Column(name = "CheckedCode",  length = 10)
	public String getCheckedCode() {
		return this.checkedCode;
	}

	public void setCheckedCode(String checkedCode) {
		this.checkedCode = checkedCode;
	}

	@Column(name = "ErrorInfo", length = 4000)
	public String getErrorInfo() {
		return this.errorInfo;
	}

	public void setErrorInfo(String errorInfo) {
		this.errorInfo = errorInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Checkdate", length = 7)
	public Date getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	@Column(name = "Temp", length = 4000)
	public String getTemp() {
		return this.temp;
	}

	public void setTemp(String temp) {
		this.temp = temp;
	}

	@Column(name = "RowNo", length = 8)
	public String getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(String rowNo) {
		this.rowNo = rowNo;
	}

	@Column(name = "ModifyState", length = 8)
	public String getModifyState() {
		return this.modifyState;
	}

	public void setModifyState(String modifyState) {
		this.modifyState = modifyState;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UpdateTime", length = 7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "UpdateOperator")
	public String getUpdateOperator() {
		return this.updateOperator;
	}

	public void setUpdateOperator(String updateOperator) {
		this.updateOperator = updateOperator;
	}

	@Column(name = "ModifyLock", length = 8)
	public String getModifyLock() {
		return this.modifyLock;
	}

	public void setModifyLock(String modifyLock) {
		this.modifyLock = modifyLock;
	}

}
