package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CfUploadDocument generated by hbm2java
 */
@Entity
@Table(name = "CfUploadDocument")
public class CfUploadDocument implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int uploadno;
	@Column
	private String reportrate;
	@Column
	private String reporttype;
	@Column
	private String reportname;
	@Column
	private String yearmonth;
	@Column
	private String quarter;
	@Column
	private String filename;
	@Column
	private String filepath;
	@Column
	private String isupflag;
	@Column
	private String operator;
	@Column
	private String operatdate;
	@Column
	private String remark;
	
	public int getUploadno() {
		return uploadno;
	}
	public void setUploadno(int uploadno) {
		this.uploadno = uploadno;
	}
	public String getReportrate() {
		return reportrate;
	}
	public void setReportrate(String reportrate) {
		this.reportrate = reportrate;
	}
	public String getReporttype() {
		return reporttype;
	}
	public void setReporttype(String reporttype) {
		this.reporttype = reporttype;
	}
	public String getReportname() {
		return reportname;
	}
	public void setReportname(String reportname) {
		this.reportname = reportname;
	}
	public String getYearmonth() {
		return yearmonth;
	}
	public void setYearmonth(String yearmonth) {
		this.yearmonth = yearmonth;
	}
	public String getQuarter() {
		return quarter;
	}
	public void setQuarter(String quarter) {
		this.quarter = quarter;
	}
	public String getFilename() {
		return filename;
	}
	public void setFilename(String filename) {
		this.filename = filename;
	}
	public String getFilepath() {
		return filepath;
	}
	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}
	public String getIsupflag() {
		return isupflag;
	}
	public void setIsupflag(String isupflag) {
		this.isupflag = isupflag;
	}
	public String getOperator() {
		return operator;
	}
	public void setOperator(String operator) {
		this.operator = operator;
	}
	public String getOperatdate() {
		return operatdate;
	}
	public void setOperatdate(String operatdate) {
		this.operatdate = operatdate;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
}
