package com.sinosoft.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Cux_Sino_Interface_HS300StockId generated by hbm2java
 */
@Embeddable
public class Cux_Sino_Interface_HS300StockId implements java.io.Serializable {
	@Column
	private String yearMonth;
	@Column
	private String code;
	@Column
	private String name;
	public String getYearMonth() {
		return yearMonth;
	}
	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Cux_Sino_Interface_HS300StockId(String yearMonth, String code, String name) {
		super();
		this.yearMonth = yearMonth;
		this.code = code;
		this.name = name;
	}
	public Cux_Sino_Interface_HS300StockId() {
		super();
	}
	
}
