package com.sinosoft.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cux_Sino_Interface_Finance generated by hbm2java
 */
@Entity
@Table(name = "Cux_Sino_Interface_Finance")
public class Cux_Sino_Interface_Finance {
	  @EmbeddedId
	  @AttributeOverrides({
			@AttributeOverride(name = "financeType", column = @Column(name = "FinanceType", nullable = false, length = 20)),
			@AttributeOverride(name = "yearMonth", column = @Column(name = "YearMonth", nullable = false, length = 20)),
			@AttributeOverride(name = "securitiesCode", column = @Column(name = "SecuritiesCode", nullable = false, length = 20)),
			@AttributeOverride(name = "securityName", column = @Column(name = "SecurityName", nullable = false, length = 200)) })
	  private Cux_Sino_Interface_FinanceId id;
	  @Column
	  private Date impDate;
	  @Column
	  private String impOperator;
	  @Column
	  private Date updateDate;
	  @Column
	  private String updateOperator;
	  @Column
	  private Date dataDate;
	  @Column
	  private String issuers;
	  @Column
	  private String currency;
	  @Column
	  private Date startDate;
	  @Column
	  private Date endDate;
	  @Column
	  private String simpleOrCompound;
	  @Column
	  private BigDecimal perDenomination;
	  @Column
	  private String profitType;
	  @Column
	  private String detailType;
	  @Column
	  private Date interestStartDate;
	  @Column
	  private Date interestFristPayDate;
	  @Column
	  private String interestPayRate;
	  @Column
	  private String interestComputeWay;
	  @Column
	  private String updateOpera;
	  @Column
	  private String confirmOpera;
	  @Column
	  private String remark;
	  @Column
	  private String riskType;
	  @Column
	  private String spare1;
	  @Column
	  private String spare2;
	  @Column
	  private String spare3;
	  @Column
	  private String spare4;
	  @Column
	  private String spare5;
	  @Column
	  private String spare6;
	  @Column
	  private String spare7;
	  @Column
	  private String spare8;
	  @Column
	  private String spare9;
	  @Column
	  private String spare10;
	public Cux_Sino_Interface_FinanceId getId() {
		return id;
	}
	public void setId(Cux_Sino_Interface_FinanceId id) {
		this.id = id;
	}
	public Date getImpDate() {
		return impDate;
	}
	public void setImpDate(Date impDate) {
		this.impDate = impDate;
	}
	public String getImpOperator() {
		return impOperator;
	}
	public void setImpOperator(String impOperator) {
		this.impOperator = impOperator;
	}
	public Date getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	public String getUpdateOperator() {
		return updateOperator;
	}
	public void setUpdateOperator(String updateOperator) {
		this.updateOperator = updateOperator;
	}
	public Date getDataDate() {
		return dataDate;
	}
	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}
	public String getIssuers() {
		return issuers;
	}
	public void setIssuers(String issuers) {
		this.issuers = issuers;
	}
	public String getCurrency() {
		return currency;
	}
	public void setCurrency(String currency) {
		this.currency = currency;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public String getSimpleOrCompound() {
		return simpleOrCompound;
	}
	public void setSimpleOrCompound(String simpleOrCompound) {
		this.simpleOrCompound = simpleOrCompound;
	}
	public BigDecimal getPerDenomination() {
		return perDenomination;
	}
	public void setPerDenomination(BigDecimal perDenomination) {
		this.perDenomination = perDenomination;
	}
	public String getProfitType() {
		return profitType;
	}
	public void setProfitType(String profitType) {
		this.profitType = profitType;
	}
	public String getDetailType() {
		return detailType;
	}
	public void setDetailType(String detailType) {
		this.detailType = detailType;
	}
	public Date getInterestStartDate() {
		return interestStartDate;
	}
	public void setInterestStartDate(Date interestStartDate) {
		this.interestStartDate = interestStartDate;
	}
	public Date getInterestFristPayDate() {
		return interestFristPayDate;
	}
	public void setInterestFristPayDate(Date interestFristPayDate) {
		this.interestFristPayDate = interestFristPayDate;
	}
	public String getInterestPayRate() {
		return interestPayRate;
	}
	public void setInterestPayRate(String interestPayRate) {
		this.interestPayRate = interestPayRate;
	}
	public String getInterestComputeWay() {
		return interestComputeWay;
	}
	public void setInterestComputeWay(String interestComputeWay) {
		this.interestComputeWay = interestComputeWay;
	}
	public String getUpdateOpera() {
		return updateOpera;
	}
	public void setUpdateOpera(String updateOpera) {
		this.updateOpera = updateOpera;
	}
	public String getConfirmOpera() {
		return confirmOpera;
	}
	public void setConfirmOpera(String confirmOpera) {
		this.confirmOpera = confirmOpera;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getRiskType() {
		return riskType;
	}
	public void setRiskType(String riskType) {
		this.riskType = riskType;
	}
	public String getSpare1() {
		return spare1;
	}
	public void setSpare1(String spare1) {
		this.spare1 = spare1;
	}
	public String getSpare2() {
		return spare2;
	}
	public void setSpare2(String spare2) {
		this.spare2 = spare2;
	}
	public String getSpare3() {
		return spare3;
	}
	public void setSpare3(String spare3) {
		this.spare3 = spare3;
	}
	public String getSpare4() {
		return spare4;
	}
	public void setSpare4(String spare4) {
		this.spare4 = spare4;
	}
	public String getSpare5() {
		return spare5;
	}
	public void setSpare5(String spare5) {
		this.spare5 = spare5;
	}
	public String getSpare6() {
		return spare6;
	}
	public void setSpare6(String spare6) {
		this.spare6 = spare6;
	}
	public String getSpare7() {
		return spare7;
	}
	public void setSpare7(String spare7) {
		this.spare7 = spare7;
	}
	public String getSpare8() {
		return spare8;
	}
	public void setSpare8(String spare8) {
		this.spare8 = spare8;
	}
	public String getSpare9() {
		return spare9;
	}
	public void setSpare9(String spare9) {
		this.spare9 = spare9;
	}
	public String getSpare10() {
		return spare10;
	}
	public void setSpare10(String spare10) {
		this.spare10 = spare10;
	}
	   
}
