package com.sinosoft.entity;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cux_Sino_Interface_Fund generated by hbm2java
 */
@Entity
@Table(name = "Cux_Sino_Interface_Fund")
public class Cux_Sino_Interface_Fund {
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "yearMonth", column = @Column(name = "YearMonth", nullable = false, length = 20)),
            @AttributeOverride(name = "securityCode", column = @Column(name = "SecurityCode", nullable = false, length = 20)),
            @AttributeOverride(name = "securityName", column = @Column(name = "SecurityName", nullable = false, length = 50))})
	private Cux_Sino_Interface_FundId id;
	private Date impDate;
	private String impOperator;
	private Date updateDate;
	private String updateOperator;
	private Date dataDate;
	private String fundPromoter;
	private String investType;
	private String gradingFund;
	private String gradingFundType;
	private String spare1;
	private String spare2;
	private String spare3;
	private String spare4;
	private String spare5;
	public Cux_Sino_Interface_FundId getId() {
		return id;
	}
	public void setId(Cux_Sino_Interface_FundId id) {
		this.id = id;
	}
	public Date getImpDate() {
		return impDate;
	}
	public void setImpDate(Date impDate) {
		this.impDate = impDate;
	}
	public String getImpOperator() {
		return impOperator;
	}
	public void setImpOperator(String impOperator) {
		this.impOperator = impOperator;
	}
	public Date getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	public String getUpdateOperator() {
		return updateOperator;
	}
	public void setUpdateOperator(String updateOperator) {
		this.updateOperator = updateOperator;
	}
	public Date getDataDate() {
		return dataDate;
	}
	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}
	public String getFundPromoter() {
		return fundPromoter;
	}
	public void setFundPromoter(String fundPromoter) {
		this.fundPromoter = fundPromoter;
	}
	public String getInvestType() {
		return investType;
	}
	public void setInvestType(String investType) {
		this.investType = investType;
	}
	public String getGradingFund() {
		return gradingFund;
	}
	public void setGradingFund(String gradingFund) {
		this.gradingFund = gradingFund;
	}
	public String getGradingFundType() {
		return gradingFundType;
	}
	public void setGradingFundType(String gradingFundType) {
		this.gradingFundType = gradingFundType;
	}
	public String getSpare1() {
		return spare1;
	}
	public void setSpare1(String spare1) {
		this.spare1 = spare1;
	}
	public String getSpare2() {
		return spare2;
	}
	public void setSpare2(String spare2) {
		this.spare2 = spare2;
	}
	public String getSpare3() {
		return spare3;
	}
	public void setSpare3(String spare3) {
		this.spare3 = spare3;
	}
	public String getSpare4() {
		return spare4;
	}
	public void setSpare4(String spare4) {
		this.spare4 = spare4;
	}
	public String getSpare5() {
		return spare5;
	}
	public void setSpare5(String spare5) {
		this.spare5 = spare5;
	}
}
