package com.sinosoft.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Cux_Sino_Interface_DepositId generated by hbm2java
 */
@Embeddable
public class Cux_Sino_Interface_FinanceId implements java.io.Serializable{
	@Column
	private String financeType;
	@Column
	private String yearMonth;
	@Column
	private String securitiesCode;
	@Column
	private String securityName;	
	public String getFinanceType() {
		return financeType;
	}
	public void setFinanceType(String financeType) {
		this.financeType = financeType;
	}
	public String getYearMonth() {
		return yearMonth;
	}
	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}
	public Cux_Sino_Interface_FinanceId(String financeType, String yearMonth, String securitiesCode,
			String securityName) {
		super();
		this.financeType = financeType;
		this.yearMonth = yearMonth;
		this.securitiesCode = securitiesCode;
		this.securityName = securityName;
	}
	public Cux_Sino_Interface_FinanceId() {
		super();
	}
	public String getSecuritiesCode() {
		return securitiesCode;
	}
	public void setSecuritiesCode(String securitiesCode) {
		this.securitiesCode = securitiesCode;
	}
	public String getSecurityName() {
		return securityName;
	}
	public void setSecurityName(String securityName) {
		this.securityName = securityName;
	}
	
}
