package com.sinosoft.entity;

// Generated 2016-1-13 19:05:16 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CfReportItemCodeDesc generated by hbm2java
 */
@Entity
@Table(name = "rsys_CfReportItemCodeDesc")
public class OCfReportItemCodeDesc implements java.io.Serializable {

	private String reportItemCode;
	private String reportItemName;
	private String rowComputePara;
	private String rowReportItemCode;
	private String rowReportItemName;
	private String colComputePara;
	private String colReportItemCode;
	private String colReportItemName;
	private String reportCode;
	private String importSource;
	private String reportItemDesc;
	private String computeLevel;
	private String isDetailExits;
	private String isDataUpdate;
	private String reportItemType;
	private String composeFormula;
	private String composeFormulaName;
	private String composeFlag;
	private String reportType;
	private String outItemCode;
	private String outItemType;
	private String outItemState;
	private String outItemNote;
	private String outItemVersion;
	private Date outItemCreatTime;
	private String propertyInsurance1;
	private String propertyInsurance2;
	private String propertyInsurance3;
	private String reinsurance;
	private String lifeInsurance1;
	private String lifeInsurance2;
	private String lifeInsurance3;
	private String lifeInsurance4;
	private String asset;
	private String group1;
	private String group2;
	private String group3;
	private String quarterReport;
	private String halfYearReport;
	private String yearReport;
	private String temp1;
	private String temp2;
	private String temp3;
	private String reportItemDescForYear;
	private String decimals;

	public OCfReportItemCodeDesc() {
	}

	public OCfReportItemCodeDesc(String reportItemCode) {
		this.reportItemCode = reportItemCode;
	}

	public OCfReportItemCodeDesc(String reportItemCode, String reportItemName,
			String rowComputePara, String rowReportItemCode,
			String rowReportItemName, String colComputePara,
			String colReportItemCode, String colReportItemName,
			String reportCode, String importSource, String reportItemDesc,
			String computeLevel, String isDetailExits, String isDataUpdate,
			String reportItemType, String composeFormula,
			String composeFormulaName, String composeFlag, String reportType,
			String outItemCode, String outItemType, String outItemState,
			String outItemNote, String outItemVersion, Date outItemCreatTime,
			String propertyInsurance1, String propertyInsurance2,
			String propertyInsurance3, String reinsurance,
			String lifeInsurance1, String lifeInsurance2,
			String lifeInsurance3, String lifeInsurance4, String asset,
			String group1, String group2, String group3, String quarterReport,
			String halfYearReport, String yearReport, String temp1,
			String temp2, String temp3, String reportItemDescForYear,String decimals) {
		this.reportItemCode = reportItemCode;
		this.reportItemName = reportItemName;
		this.rowComputePara = rowComputePara;
		this.rowReportItemCode = rowReportItemCode;
		this.rowReportItemName = rowReportItemName;
		this.colComputePara = colComputePara;
		this.colReportItemCode = colReportItemCode;
		this.colReportItemName = colReportItemName;
		this.reportCode = reportCode;
		this.importSource = importSource;
		this.reportItemDesc = reportItemDesc;
		this.computeLevel = computeLevel;
		this.isDetailExits = isDetailExits;
		this.isDataUpdate = isDataUpdate;
		this.reportItemType = reportItemType;
		this.composeFormula = composeFormula;
		this.composeFormulaName = composeFormulaName;
		this.composeFlag = composeFlag;
		this.reportType = reportType;
		this.outItemCode = outItemCode;
		this.outItemType = outItemType;
		this.outItemState = outItemState;
		this.outItemNote = outItemNote;
		this.outItemVersion = outItemVersion;
		this.outItemCreatTime = outItemCreatTime;
		this.propertyInsurance1 = propertyInsurance1;
		this.propertyInsurance2 = propertyInsurance2;
		this.propertyInsurance3 = propertyInsurance3;
		this.reinsurance = reinsurance;
		this.lifeInsurance1 = lifeInsurance1;
		this.lifeInsurance2 = lifeInsurance2;
		this.lifeInsurance3 = lifeInsurance3;
		this.lifeInsurance4 = lifeInsurance4;
		this.asset = asset;
		this.group1 = group1;
		this.group2 = group2;
		this.group3 = group3;
		this.quarterReport = quarterReport;
		this.halfYearReport = halfYearReport;
		this.yearReport = yearReport;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.reportItemDescForYear = reportItemDescForYear;
		this.decimals = decimals;
	}

	@Id
	@Column(name = "ReportItemCode", unique = true, nullable = false, length = 20)
	public String getReportItemCode() {
		return this.reportItemCode;
	}

	public void setReportItemCode(String reportItemCode) {
		this.reportItemCode = reportItemCode;
	}

	@Column(name = "ReportItemName", length = 200)
	public String getReportItemName() {
		return this.reportItemName;
	}

	public void setReportItemName(String reportItemName) {
		this.reportItemName = reportItemName;
	}
	@Column(name = "decimals", length = 20)
	public String getDecimals() {
		return decimals;
	}

	public void setDecimals(String decimals) {
		this.decimals = decimals;
	}

	@Column(name = "RowComputePara", length = 20)
	public String getRowComputePara() {
		return this.rowComputePara;
	}

	public void setRowComputePara(String rowComputePara) {
		this.rowComputePara = rowComputePara;
	}

	@Column(name = "RowReportItemCode", length = 10)
	public String getRowReportItemCode() {
		return this.rowReportItemCode;
	}

	public void setRowReportItemCode(String rowReportItemCode) {
		this.rowReportItemCode = rowReportItemCode;
	}

	@Column(name = "RowReportItemName", length = 200)
	public String getRowReportItemName() {
		return this.rowReportItemName;
	}

	public void setRowReportItemName(String rowReportItemName) {
		this.rowReportItemName = rowReportItemName;
	}

	@Column(name = "ColComputePara", length = 20)
	public String getColComputePara() {
		return this.colComputePara;
	}

	public void setColComputePara(String colComputePara) {
		this.colComputePara = colComputePara;
	}

	@Column(name = "ColReportItemCode", length = 10)
	public String getColReportItemCode() {
		return this.colReportItemCode;
	}

	public void setColReportItemCode(String colReportItemCode) {
		this.colReportItemCode = colReportItemCode;
	}

	@Column(name = "ColReportItemName", length = 200)
	public String getColReportItemName() {
		return this.colReportItemName;
	}

	public void setColReportItemName(String colReportItemName) {
		this.colReportItemName = colReportItemName;
	}

	@Column(name = "ReportCode", length = 20)
	public String getReportCode() {
		return this.reportCode;
	}

	public void setReportCode(String reportCode) {
		this.reportCode = reportCode;
	}

	@Column(name = "ImportSource", length = 1)
	public String getImportSource() {
		return this.importSource;
	}

	public void setImportSource(String importSource) {
		this.importSource = importSource;
	}

	@Column(name = "ReportItemDesc", length = 4000)
	public String getReportItemDesc() {
		return this.reportItemDesc;
	}

	public void setReportItemDesc(String reportItemDesc) {
		this.reportItemDesc = reportItemDesc;
	}

	@Column(name = "ComputeLevel", length = 2)
	public String getComputeLevel() {
		return this.computeLevel;
	}

	public void setComputeLevel(String computeLevel) {
		this.computeLevel = computeLevel;
	}

	@Column(name = "IsDetailExits", length = 1)
	public String getIsDetailExits() {
		return this.isDetailExits;
	}

	public void setIsDetailExits(String isDetailExits) {
		this.isDetailExits = isDetailExits;
	}

	@Column(name = "IsDataUpdate", length = 1)
	public String getIsDataUpdate() {
		return this.isDataUpdate;
	}

	public void setIsDataUpdate(String isDataUpdate) {
		this.isDataUpdate = isDataUpdate;
	}

	@Column(name = "ReportItemType", length = 2)
	public String getReportItemType() {
		return this.reportItemType;
	}

	public void setReportItemType(String reportItemType) {
		this.reportItemType = reportItemType;
	}

	@Column(name = "ComposeFormula", length = 1000)
	public String getComposeFormula() {
		return this.composeFormula;
	}

	public void setComposeFormula(String composeFormula) {
		this.composeFormula = composeFormula;
	}

	@Column(name = "ComposeFormulaName", length = 3000)
	public String getComposeFormulaName() {
		return this.composeFormulaName;
	}

	public void setComposeFormulaName(String composeFormulaName) {
		this.composeFormulaName = composeFormulaName;
	}

	@Column(name = "ComposeFlag", length = 1)
	public String getComposeFlag() {
		return this.composeFlag;
	}

	public void setComposeFlag(String composeFlag) {
		this.composeFlag = composeFlag;
	}

	@Column(name = "ReportType", length = 2)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Column(name = "OutItemCode", length = 20)
	public String getOutItemCode() {
		return this.outItemCode;
	}

	public void setOutItemCode(String outItemCode) {
		this.outItemCode = outItemCode;
	}

	@Column(name = "OutItemType", length = 2)
	public String getOutItemType() {
		return this.outItemType;
	}

	public void setOutItemType(String outItemType) {
		this.outItemType = outItemType;
	}

	@Column(name = "OutItemState", length = 1)
	public String getOutItemState() {
		return this.outItemState;
	}

	public void setOutItemState(String outItemState) {
		this.outItemState = outItemState;
	}

	@Column(name = "OutItemNote", length = 1000)
	public String getOutItemNote() {
		return this.outItemNote;
	}

	public void setOutItemNote(String outItemNote) {
		this.outItemNote = outItemNote;
	}

	@Column(name = "OutItemVersion", length = 1)
	public String getOutItemVersion() {
		return this.outItemVersion;
	}

	public void setOutItemVersion(String outItemVersion) {
		this.outItemVersion = outItemVersion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OutItemCreatTime", length = 7)
	public Date getOutItemCreatTime() {
		return this.outItemCreatTime;
	}

	public void setOutItemCreatTime(Date outItemCreatTime) {
		this.outItemCreatTime = outItemCreatTime;
	}

	@Column(name = "PropertyInsurance1", length = 1)
	public String getPropertyInsurance1() {
		return this.propertyInsurance1;
	}

	public void setPropertyInsurance1(String propertyInsurance1) {
		this.propertyInsurance1 = propertyInsurance1;
	}

	@Column(name = "PropertyInsurance2", length = 1)
	public String getPropertyInsurance2() {
		return this.propertyInsurance2;
	}

	public void setPropertyInsurance2(String propertyInsurance2) {
		this.propertyInsurance2 = propertyInsurance2;
	}

	@Column(name = "PropertyInsurance3", length = 1)
	public String getPropertyInsurance3() {
		return this.propertyInsurance3;
	}

	public void setPropertyInsurance3(String propertyInsurance3) {
		this.propertyInsurance3 = propertyInsurance3;
	}

	@Column(name = "Reinsurance", length = 1)
	public String getReinsurance() {
		return this.reinsurance;
	}

	public void setReinsurance(String reinsurance) {
		this.reinsurance = reinsurance;
	}

	@Column(name = "LifeInsurance1", length = 1)
	public String getLifeInsurance1() {
		return this.lifeInsurance1;
	}

	public void setLifeInsurance1(String lifeInsurance1) {
		this.lifeInsurance1 = lifeInsurance1;
	}

	@Column(name = "LifeInsurance2", length = 1)
	public String getLifeInsurance2() {
		return this.lifeInsurance2;
	}

	public void setLifeInsurance2(String lifeInsurance2) {
		this.lifeInsurance2 = lifeInsurance2;
	}

	@Column(name = "LifeInsurance3", length = 1)
	public String getLifeInsurance3() {
		return this.lifeInsurance3;
	}

	public void setLifeInsurance3(String lifeInsurance3) {
		this.lifeInsurance3 = lifeInsurance3;
	}

	@Column(name = "LifeInsurance4", length = 1)
	public String getLifeInsurance4() {
		return this.lifeInsurance4;
	}

	public void setLifeInsurance4(String lifeInsurance4) {
		this.lifeInsurance4 = lifeInsurance4;
	}

	@Column(name = "Asset", length = 1)
	public String getAsset() {
		return this.asset;
	}

	public void setAsset(String asset) {
		this.asset = asset;
	}

	@Column(name = "Group1", length = 1)
	public String getGroup1() {
		return this.group1;
	}

	public void setGroup1(String group1) {
		this.group1 = group1;
	}

	@Column(name = "Group2", length = 1)
	public String getGroup2() {
		return this.group2;
	}

	public void setGroup2(String group2) {
		this.group2 = group2;
	}

	@Column(name = "Group3", length = 1)
	public String getGroup3() {
		return this.group3;
	}

	public void setGroup3(String group3) {
		this.group3 = group3;
	}

	@Column(name = "QuarterReport", length = 1)
	public String getQuarterReport() {
		return this.quarterReport;
	}

	public void setQuarterReport(String quarterReport) {
		this.quarterReport = quarterReport;
	}

	@Column(name = "HalfYearReport", length = 1)
	public String getHalfYearReport() {
		return this.halfYearReport;
	}

	public void setHalfYearReport(String halfYearReport) {
		this.halfYearReport = halfYearReport;
	}

	@Column(name = "YearReport", length = 1)
	public String getYearReport() {
		return this.yearReport;
	}

	public void setYearReport(String yearReport) {
		this.yearReport = yearReport;
	}

	@Column(name = "Temp1")
	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	@Column(name = "Temp2")
	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	@Column(name = "Temp3")
	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	@Column(name = "ReportItemDescForYear", length = 20)
	public String getReportItemDescForYear() {
		return this.reportItemDescForYear;
	}

	public void setReportItemDescForYear(String reportItemDescForYear) {
		this.reportItemDescForYear = reportItemDescForYear;
	}

}
